---
name: Development Pipeline

"on":
  push:
    branches:
      - "**"

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          go clean -testcache
          go test -v -cover -race ./...

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Build binary
        run: |
          just tidy
          just build

      - name: Verify binary build
        run: |
          ./jwtview --help

      - name: Fetch OIDC token
        id: fetch-token
        run: |
          AUDIENCE="https://www.github.com"

          OIDC_TOKEN=$(curl -sSL -X GET "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')

          echo "::add-mask::$OIDC_TOKEN"
          echo "gha-oidc-token=$OIDC_TOKEN" >> $GITHUB_OUTPUT

      - name: Test OIDC token with CLI
        run: |
          ./jwtview ${{ steps.fetch-token.outputs.gha-oidc-token }} > parsed.json
          echo "Issuer: $(jq -r '.iss' parsed.json)"
          echo "Audience: $(jq -r '.aud' parsed.json)"
          echo "Expiration: $(jq -r '.exp' parsed.json)"
