---
name: Development Pipeline

"on":
  push:
    branches:
      - "**"

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up workspace
        uses: ./.github/actions/setup-workspace

      - name: Unit tests
        run: |
          go clean -testcache
          go test -v -cover -race ./...

  system-test:
    name: Run System Tests
    runs-on: ubuntu-latest
    needs: unit-test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up workspace
        uses: ./.github/actions/setup-workspace

      - name: Build binary
        run: |
          just tidy
          just build

      - name: Verify binary build
        run: |
          ./jwtview --help

      - name: Test CLI against OIDC token
        run: |
          set -euo pipefail
          AUDIENCE="https://www.github.com"

          OIDC_TOKEN=$(curl --fail-with-body -sSL -X GET "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -er '.value')

          printf '::add-mask::%s\n' "$OIDC_TOKEN"
          PARSED_JSON=$(./jwtview -vv "$OIDC_TOKEN" | jq -c .)
          printf '::add-mask::%s\n' "$PARSED_JSON"
          echo "Issuer: $(jq -er '.payload.iss' <<< "${PARSED_JSON}")"
          echo "Workflow Ref: $(jq -er '.payload.job_workflow_ref' <<< "${PARSED_JSON}")"
          echo "Workflow SHA: $(jq -er '.payload.workflow_sha' <<< "${PARSED_JSON}")"
